services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: hms_migrator
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: hms
    ports:
      - "5432:5432"
    volumes:
      - hms_pgdata:/var/lib/postgresql

volumes:
  hms_pgdata:
