/**
 * modules/identity/schema.ts
 *
 * Identity & access: users, per-user permission overrides.
 * Owned tables (blueprint §5.1 module map): users, user_permission_overrides.
 * rate_limit_attempts is cross-cutting DDL and lives in core/db/infra.ts
 * (the DB-backed limiter in core/rate-limit writes it; core may not import
 * module schemas).
 *
 * Enums user_role / user_status are defined here. Other modules that reference
 * `user_role` (audit) re-declare it with identical values — the Postgres type is
 * shared by name. Better Auth's own session/account/verification tables are
 * generated by its CLI in the identity phase and appended to this file.
 *
 * Column keys are camelCase; the drizzle client runs with casing:'snake_case' so
 * they map 1:1 to the snake_case DDL in drizzle/0001_full_schema.sql §4.
 * Cross-module FKs (users.property_id → properties, users.created_by → users) are
 * enforced by the migration, not repeated here.
 */
import { sql } from 'drizzle-orm';
import { boolean, index, pgEnum, pgTable, primaryKey, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';

export const userRole = pgEnum('user_role', ['admin', 'manager', 'receptionist']);
export const userStatus = pgEnum('user_status', ['active', 'suspended', 'disabled']);

export const users = pgTable(
  'users',
  {
    id: uuid('id').primaryKey().default(sql`new_id()`),
    name: text('name').notNull(),
    email: text('email').notNull(),
    emailVerified: boolean('email_verified').notNull().default(false),
    image: text('image'),
    role: userRole('role').notNull().default('receptionist'),
    status: userStatus('status').notNull().default('active'),
    phone: text('phone'),
    propertyId: uuid('property_id'),
    mustChangePassword: boolean('must_change_password').notNull().default(true),
    passwordChangedAt: timestamp('password_changed_at', { withTimezone: true }),
    lastLoginAt: timestamp('last_login_at', { withTimezone: true }),
    twoFactorEnabled: boolean('two_factor_enabled').notNull().default(false),
    createdBy: uuid('created_by'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
  },
  (t) => [
    uniqueIndex('users_email_lower_uq')
      .on(sql`lower(${t.email})`)
      .where(sql`${t.deletedAt} IS NULL`),
    index('users_role_idx').on(t.role).where(sql`${t.deletedAt} IS NULL`),
  ],
);

export const userPermissionOverrides = pgTable(
  'user_permission_overrides',
  {
    userId: uuid('user_id').notNull(),
    permission: text('permission').notNull(),
    allowed: boolean('allowed').notNull(),
    grantedBy: uuid('granted_by'),
    reason: text('reason'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.permission] })],
);